on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'testing Gitnub action'
        run: pwd

      - name: 'before'
        run: ls


      - uses: action/checkout@v3

      - name: 'after'
        run: ls
